### ISSUE TITLE
unnecessary role usage

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-spring-security-mvc-sample#10]
(AUTH-3595)
As discussed here https://github.com/auth0-samples/auth0-spring-security-mvc-sample/issues/5, first samples don't need to use [authentication through roles](https://github.com/auth0-samples/auth0-spring-security-mvc-sample/blob/master/01-Login/src/main/java/com/auth0/example/AppConfig.java#L23). Possible fix: #9

**Comment by HeikerAraujo** [comment]
(AUTH-3891) Samples don't need to use authentication through roles.
(Same situation is presented both for the tutorial of the page and for the sample project)

Tutorial page

![unnecessaryroleusage](https://cloud.githubusercontent.com/assets/26749061/24736282/1248cc3a-1a55-11e7-99d5-5ec9724900e0.jpg)

Sample project AppConfig.java

![unnecessaryroleusage](https://cloud.githubusercontent.com/assets/26749061/24736322/563849f2-1a55-11e7-80e5-4236c32a53ec.png)

**Comment by jimmyjames** [comment]
As this issue is a few years old and the product, sample, and supporting SDKs have changed significantly in that time, I'm going to close this issue. If you still have difficulties, don't hesitate to reopen this issue or create a new one (just be sure to include updated debugging information). Thanks!
