### ISSUE TITLE
error controller - better options ?

### ISSUE THREAD

**Issue by AndreiD** [auth0-samples/auth0-spring-security-mvc-sample#17]
Greetings,

The error controller redirects to /login for all kinds of errors (like 404...)
Why is this? Shouldn't it redirect to /login for 403 only....and for the other types of errors just show a custom error page etc.

am I missing something ?

**Comment by jimmyjames** [comment]
Hi @AndreiD, as this issue is nearly two years old and the sample code and supporting SDKs have been updated since then, I'm going to close this issue. If you continue to have difficulties, don't hesitate to reopen this issue or create a new one (just be sure to include updated debugging information). Thanks!
